name: gplx_vn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.7
  time_picker_spinner: ^1.0.2
  firebase_core: ^2.30.0
  flutter_local_notifications: ^16.3.2
  flutter_native_timezone: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  assets:
    - assets/configs_a1.json
    - assets/configs_a2.json
    - assets/configs_b1.json
    - assets/configs_b2.json
    - assets/configs_c.json
    - assets/configs_d.json
    - assets/configs_e.json
    - assets/configs_f.json
    - assets/exams_a1.json
    - assets/exams_a2.json
    - assets/exams_b1.json
    - assets/exams_b2.json
    - assets/exams_c.json
    - assets/exams_d.json
    - assets/exams_e.json
    - assets/exams_f.json
    - assets/images/
    - assets/license_types.json
    - assets/quizzes_a1.json
    - assets/quizzes_a2.json
    - assets/quizzes_b1.json
    - assets/quizzes_b2_bk.json
    - assets/quizzes_b2.json
    - assets/quizzes_c.json
    - assets/quizzes_d.json
    - assets/quizzes_e.json
    - assets/quizzes_f.json
    - assets/topics_a1.json
    - assets/topics_a2.json
    - assets/topics_b1.json
    - assets/topics_b2.json
    - assets/topics_c.json
    - assets/topics_d.json
    - assets/topics_e.json
    - assets/topics_f.json
    - assets/traffic_signs.json
    - assets/road_diagram_a1.json
    - assets/road_diagram_a2.json
    - assets/road_diagram_b1.json
    - assets/road_diagram_b2.json
    - assets/road_diagram_c.json
    - assets/road_diagram_d.json
    - assets/road_diagram_e.json
    - assets/road_diagram_f.json
    - assets/tips_a1.json
    - assets/tips_a2.json
    - assets/tips_b1.json
    - assets/tips_b2.json
    - assets/tips_c.json
    - assets/tips_d.json
    - assets/tips_e.json
    - assets/tips_f.json

  uses-material-design: true
  # fonts: